FROM node:24-alpine3.23

RUN mkdir -p /opt/data
WORKDIR /opt/service

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY src ./src
COPY tsconfig.json ./tsconfig.json

ENTRYPOINT ["npm", "start"]
